name: starshot
recipe: drupal10
config:
  webroot: web
tooling:
  drupal:install:
    service: appserver
    cmd: |
      composer install
      composer drupal:install
      echo ""
      echo "🚀 Board the spaceship!"
      echo "👇 Click on the link below to login 👇"
      drush uli -l 'https://starshot.lndo.site'
      echo ""
